# Generated by Django 3.2.9 on 2022-01-17 00:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0017_auto_20220114_1235'),
        ('profiles', '0002_wishlistadd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishListAdd',
            new_name='WishListItem',
        ),
    ]
