# Generated by Django 3.2.9 on 2022-01-03 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('art_nr', models.CharField(max_length=254, verbose_name='Art. Nr')),
                ('description', models.TextField(verbose_name='Description')),
                ('gender', models.CharField(choices=[('W', 'Womens'), ('M', 'Mens'), ('U', 'Unisex')], max_length=1, verbose_name='Gender')),
                ('brand', models.CharField(max_length=254, verbose_name='Brand')),
                ('details', models.CharField(blank=True, max_length=254, null=True, verbose_name='Product Details')),
                ('size_type', models.BooleanField(blank=True, choices=[('Sizes', (('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'))), ('Womens Sizes', (('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'))), ('Mens Sizes', (('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'))), ('Sock Sizes', (('34-37', '34-37'), ('38-41', '38-41'), ('42-45', '42-45'), ('46-50', '46-50'))), ('Womens Sock Sizes', (('34-37', '34-37'), ('38-41', '38-41'), ('42-45', '42-45'))), ('Mens Sock Sizes', (('38-41', '38-41'), ('42-45', '42-45'), ('46-50', '46-50'))), ('N/A', 'N/A')], default='N/A', null=True, verbose_name='Size Type')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rating')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Discount')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Image URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rating', models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=5)),
                ('title', models.TextField(max_length=25, verbose_name='Review Title')),
                ('user_review', models.TextField(max_length=250, verbose_name='User Review')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
