# Generated by Django 3.2.9 on 2022-01-18 15:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Name')),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Image URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_nr', models.CharField(max_length=254, verbose_name='Art. Nr')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Name')),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial Price')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('gender', models.CharField(choices=[('w', 'Womens'), ('m', 'Mens'), ('u', 'Unisex')], default='u', max_length=24, verbose_name='Gender')),
                ('details', models.CharField(blank=True, max_length=254, null=True, verbose_name='Product Details')),
                ('size_type', models.CharField(choices=[('shoes', 'Shoes'), ('socks', 'Socks'), ('n_a', 'N/A')], default='N/A', max_length=24, verbose_name='Size Type')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rating')),
                ('is_new', models.BooleanField(default=False, verbose_name='Is New')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Discount')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Image URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rating', models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=5)),
                ('title', models.CharField(max_length=25, verbose_name='Review Title')),
                ('user_review', models.TextField(max_length=250, verbose_name='User Review')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
