# Generated by Django 3.2.9 on 2022-01-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('w', "Women's"), ('m', "Men's"), ('u', 'Unisex')], default='u', max_length=24, verbose_name='Gender'),
        ),
    ]
