# Generated by Django 3.2.9 on 2022-01-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='friendly_name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
