# Generated by Django 3.2.9 on 2022-01-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Image URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
