# Generated by Django 3.2.9 on 2022-01-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_size_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Womens', 'w'), ('Mens', 'm'), ('Unisex', 'u')], max_length=24, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('socks', 'Socks'), ('N/A', 'N/A')], default='N/A', max_length=24, verbose_name='Size Type'),
        ),
    ]
