# Generated by Django 3.2.9 on 2022-01-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220105_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('womens', 'Womens'), ('mens', 'Mens'), ('unisex', 'Unisex')], max_length=24, verbose_name='Gender'),
        ),
    ]
