# Generated by Django 3.2.9 on 2022-01-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('w', 'Womens'), ('m', 'Mens'), ('u', 'Unisex')], max_length=24, verbose_name='Gender'),
        ),
    ]
