# Generated by Django 3.2.9 on 2022-01-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='current_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Review Title'),
        ),
    ]
