# Generated by Django 3.2.9 on 2022-01-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220111_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('socks', 'Socks'), ('n_a', 'N/A')], default='N/A', max_length=24, verbose_name='Size Type'),
        ),
    ]
